name: screenshot_callback
description: Flutter plugin that allows you to detect mobile screenshot and execute callback functions on iOS and Android.
version: 1.1.2
authors:
- Gwangyu-Kim <kwangyu326@gmail.com>
- minsub0922<minsub0922@naver.com>
- beygee<doug0476@naver.com>
- Flutter Moum <fluttermoum@gmail.com>
homepage: https://github.com/flutter-moum/flutter_screenshot_callback

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.flutter.moum.screenshot_callback
    pluginClass: ScreenshotCallbackPlugin
