name: screenshot_callback
description: Flutter plugin that allows you to detect mobile screenshot and execute callback functions on iOS and Android.
version: 2.0.1
homepage: https://github.com/flutter-moum/flutter_screenshot_callback

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.flutter.moum.screenshot_callback
        pluginClass: ScreenshotCallbackPlugin
      ios:
        pluginClass: ScreenshotCallbackPlugin
